name: CI

on:
  push:
  pull_request:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y shellcheck

      - name: List shell scripts
        id: list
        run: |
          echo "files=install-proxmox-health.sh lib/*.sh" >> $GITHUB_OUTPUT

      - name: ShellCheck (bash, follow sources)
        run: |
          # Ignore expected patterns used in this project to keep scripts concise
          # - SC1091: external config sourced at runtime
          # - SC2155: declare+assign together is allowed in this codebase
          # - SC2034: some arrays/loop vars are intentionally unused
          # - SC2030,SC2031: addressed where relevant; remaining cases are safe
          shellcheck -x -s bash -e SC1091,SC2155,SC2034,SC2030,SC2031 ${{ steps.list.outputs.files }}

      - name: Bash syntax check
        run: |
          for f in ${{ steps.list.outputs.files }}; do
            echo "Syntax check: $f"; bash -n "$f"; done

  formatting:
    name: Basic Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check for tab characters
        run: |
          echo "Checking for tab characters in source files..."
          if git grep -nI $'\t' -- ':!*.md' ':!*.txt' ':!*.json' ':!*.yml' ':!*.yaml'; then
            echo ""
            echo "❌ Tab characters found in the files above."
            echo "💡 Fix with: sed -i 's/\t/    /g' <filename>"
            echo "   Or run: find . -name '*.sh' -exec sed -i 's/\t/    /g' {} +"
            exit 1
          else
            echo "✅ No tab characters found"
          fi
      
      - name: Check for trailing whitespace (shell scripts only)
        run: |
          echo "Checking for trailing whitespace in shell scripts..."
          if git grep -nI '[[:space:]]$' -- '*.sh' '*.bash'; then
            echo ""
            echo "❌ Trailing whitespace found in the files above."
            echo "💡 Fix with (GNU sed): sed -i 's/[[:space:]]*$//' <filename>"
            echo "   macOS sed:         sed -i '' 's/[[:space:]]*$//' <filename>"
            echo "   Or run (GNU): find . -type f \\( -name '*.sh' -o -name '*.bash' \\) -exec sed -i 's/[[:space:]]*$//' {} +"
            echo "   Or run (macOS): find . -type f \\( -name '*.sh' -o -name '*.bash' \\) -exec sed -i '' 's/[[:space:]]*$//' {} +"
            exit 1
          else
            echo "✅ No trailing whitespace found"
          fi
      
      - name: Auto-fix formatting (informational)
        if: failure()
        run: |
          echo ""
          echo "🔧 Auto-fix command for all formatting issues:"
          echo "   GNU:  find . -type f \\( -name '*.sh' -o -name '*.bash' \\) -exec sed -i -e 's/\\t/    /g' -e 's/[[:space:]]*$//' {} +"
          echo "   macOS:find . -type f \\( -name '*.sh' -o -name '*.bash' \\) -exec sed -i '' -e 's/\\t/    /g' -e 's/[[:space:]]*$//' {} +"
          echo ""
          echo "Or fix individual files:"
          echo "   GNU sed:    sed -i -e 's/\\t/    /g' -e 's/[[:space:]]*$//' path/to/file.sh"
          echo "   macOS sed:  sed -i '' -e 's/\\t/    /g' -e 's/[[:space:]]*$//' path/to/file.sh"
